version: "3"

services:

  flask:
    build: node_info_app
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080

  nginx:
    image: nginx:latest
    container_name: nginx_reverseproxy
    depends_on:
        - flask
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
        - 80:80
